# Generated by Django 4.2.5 on 2023-09-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("footballweb", "0002_football_rok_alter_football_tytul"),
    ]

    operations = [
        migrations.AddField(
            model_name="football",
            name="lig_mistrzów",
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="football",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logosy"),
        ),
        migrations.AddField(
            model_name="football", name="opis", field=models.TextField(default=""),
        ),
    ]
