# Generated by Django 4.2.5 on 2023-09-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("footballweb", "0003_football_lig_mistrzów_football_logo_football_opis"),
    ]

    operations = [
        migrations.AddField(
            model_name="football",
            name="kraj",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Hiszpania"),
                    (1, "Anglia"),
                    (2, "Włochy"),
                    (3, "Niemcy"),
                    (4, "Francja"),
                    (5, "Polska"),
                    (6, "Nieznany"),
                ],
                default=6,
            ),
        ),
    ]
